# Generated by Django 5.1.4 on 2024-12-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_score_blog_score_user_id_bbf480_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='BlogPost',
        ),
    ]
